[package]
name        = "flix-files"
description = "Flix's former standard library `File` and `Files` modules."
version     = "1.0.0"
flix        = "0.54.0"
authors     = "Matthew Lutze (maintainer), Various Flix Contributors"
